# Generated by Django 5.1.7 on 2025-05-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("call", "0002_call_created_at_call_created_by_call_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="call_agenda",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="call",
            name="voice_recording",
            field=models.TextField(blank=True, null=True),
        ),
    ]
