# Generated by Django 5.1.7 on 2025-03-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_account_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="state_province",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="street",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
