# Generated by Django 5.1.7 on 2025-03-23 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="deal.stage",
            ),
        ),
    ]
