# Generated by Django 5.1.7 on 2025-03-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0003_remove_lead_name_lead_first_name_lead_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="email",
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
