# Generated by Django 5.1.7 on 2025-03-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0004_alter_lead_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
