version: '3.8'
services:
  django:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../src:/src
    command: ash -c "cd /src && daphne -b 0.0.0.0 -p 8000 api.asgi:application"
    tty: true
    depends_on:
      - redis
    env_file:
      - ../src/.env
    networks:
      - my-network
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - my-network

  celery:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: ash -c "cd /src && celery --app=api worker -l info"
    volumes:
      - ../src:/src
    depends_on:
      - redis
      - django
    env_file:
      - ../src/.env
    networks:
      - my-network

  celery-beat:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: ash -c "cd /src && celery -A api beat -l info"
    volumes:
      - ../src:/src
    depends_on:
      - redis
      - celery
    env_file:
      - ../src/.env
    networks:
      - my-network

networks:
  my-network:
    driver: bridge