# Generated by Django 5.1.7 on 2025-03-17 04:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0001_initial"),
        ("campaign_target", "0001_initial"),
        ("contact", "0002_alter_contact_avatar"),
        ("lead", "0002_alter_lead_avatar"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CampaignTargets",
            new_name="CampaignTarget",
        ),
    ]
