# Generated by Django 5.1.7 on 2025-03-17 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("lead", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("mobile", models.CharField(blank=True, max_length=20, null=True)),
                ("department", models.CharField(blank=True, max_length=255, null=True)),
                ("birthday", models.DateField(blank=True, null=True)),
                (
                    "assistant_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "assistant_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("avatar", models.URLField(blank=True, default="v1", null=True)),
                ("is_email_opt_out", models.BooleanField(default=False)),
                ("is_call_opt_out", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contacts",
                        to="account.account",
                    ),
                ),
                (
                    "contact_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contacts",
                        to="lead.leadsource",
                    ),
                ),
            ],
            options={
                "db_table": "contact",
                "ordering": ["-id"],
            },
        ),
    ]
