# Generated by Django 5.1.7 on 2025-03-17 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tag_item", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tags",
            new_name="Tag",
        ),
    ]
