# Generated by Django 5.1.7 on 2025-03-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stage_history", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stagehistory",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="stagehistory",
            name="expected_revenue",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="stagehistory",
            name="probability",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="stagehistory",
            name="stage_duration",
            field=models.IntegerField(default=0),
        ),
    ]
