# Generated by Django 5.1.7 on 2025-03-24 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deal", "0002_deal_stage"),
        (
            "stage_history",
            "0002_stagehistory_amount_stagehistory_expected_revenue_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="stagehistory",
            name="deal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stage_history",
                to="deal.deal",
            ),
        ),
    ]
