# Generated by Django 5.1.7 on 2025-05-23 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_account_city_account_country_account_postal_code_and_more"),
        ("campaign", "0001_initial"),
        ("contact", "0004_rename_mobile_contact_fax_remove_contact_name_and_more"),
        ("deal", "0002_deal_stage"),
        ("lead", "0005_lead_deleted_at_lead_is_deleted"),
        ("meeting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="related_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="account.account",
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="related_campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="campaign.campaign",
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="related_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contact.contact",
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="related_deal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="deal.deal",
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="related_lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lead.lead",
            ),
        ),
        migrations.AlterField(
            model_name="meetingparticipant",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meetings_participated",
                to="contact.contact",
            ),
        ),
        migrations.AlterField(
            model_name="meetingparticipant",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meetings_participated",
                to="lead.lead",
            ),
        ),
    ]
