# Generated by Django 5.1.7 on 2025-05-01 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0004_rename_mobile_contact_fax_remove_contact_name_and_more"),
        ("lead", "0005_lead_deleted_at_lead_is_deleted"),
        ("meeting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingparticipant",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meetings_participated",
                to="contact.contact",
            ),
        ),
        migrations.AlterField(
            model_name="meetingparticipant",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meetings_participated",
                to="lead.lead",
            ),
        ),
    ]
