# Generated by Django 5.1.7 on 2025-06-01 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0002_alter_meetingparticipant_contact_and_more"),
        ("meeting", "0002_meeting_related_account_meeting_related_campaign_and_more"),
    ]

    operations = []
